### PR TITLE
Fix multiple bugs regarding DOKubernetesCluster

### LINKED ISSUE #46: Kubernetes READY column is empty
### What happened?

READY column is empty instead of showing the status of the cluster

### How can we reproduce it?

Create a DOK cluster.

```bash
kubectl get dokubernetesclusters
```

Output:

```
NAME         READY   SYNCED
a-team-dok           True
```

### LINKED ISSUE #47: DOK kubeconfig secret not created
### What happened?

When working with Kubernetes cluster resources, Crossplane creates a secret that can be used by other resources. In case of DOK, the secret is not created.

### How can we reproduce it?

Create a DOK cluster and check whether the secrets with kubeconfig were created in `crossplane-system` and the claim Namespace (if using claims).

### PR DESCRIPTION
**Pull request by ADustyOldMuffin**
### Description of your changes
This adds the pushing of credentials for DOK8s clusters during their observe step, and also makes sure we're setting the status of the resource.

I noticed while working on this that we don't do this for a couple of resources, so I'll be making bugs for them and tackle them in other PRs.

Fixes #46
Fixes #47 

I have:

- [x] Read and followed Crossplane's [contribution process].
- [x] Run `make reviewable test` to ensure this PR is ready for review.

### How has this code been tested
I ran it on a local cluster and confirmed the resources appeared.

[contribution process]: https://git.io/fj2m9

### CODE REVIEW

**Comment by ADustyOldMuffin** [comment]
The e2e tests will fail until master is updated, I'll merge once it has.

File: apis/kubernetes/v1alpha1/kubernetescluster_types.go [hunk 1]
```diff
@@ -289,7 +292,7 @@ type KubernetesClusterMaintenancePolicyObservation struct {
 type KubernetesStatus struct {
 	// A string indicating the current status of the node.
 	// +kubebuilder:validation:Optional
-	State string `json:"state,omitempty"`
+	State KubernetesStateType `json:"state,omitempty"`
```
Comment (hasheddan) [inline apis/kubernetes/v1alpha1/kubernetescluster_types.go:295]: nitpick: I typically will omit something like `Type` as it can be inferred by the identifier being a `type`, but feel free to ignore if you are not aligned
```suggestion
	State ClusterState `json:"state,omitempty"`
```

**Review by hasheddan — APPROVED** [review]

File: apis/kubernetes/v1alpha1/kubernetescluster_types.go (hunk 1 above)
Comment (ADustyOldMuffin) [reply apis/kubernetes/v1alpha1/kubernetescluster_types.go]: Thanks! I updated it to be `KubernetesState` instead of `ClusterState` since it's also used to describe other resources such as the nodes and not just the cluster. But I do like the idea of not having type at the end.
